export const NetflixOriginals = {
  data: {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/9yBVqNruk6Ykrwc32qrK2TIE5xw.jpg",
        genre_ids: [14, 28, 12, 878, 53],
        id: 460465,
        original_language: "en",
        original_title: "Mortal Kombat",
        overview:
          "Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung's best warrior, Sub-Zero, seeks out and trains with Earth's greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.",
        popularity: 7966.615,
        poster_path: "/6Wdl9N6dL0Hi0T1qJLWSz6gMLbd.jpg",
        release_date: "2021-04-07",
        title: "Mortal Kombat",
        video: false,
        vote_average: 7.9,
        vote_count: 1747,
      },
      {
        adult: false,
        backdrop_path: "/inJjDhCjfhh3RtrJWBmmDqeuSYC.jpg",
        genre_ids: [878, 28],
        id: 399566,
        original_language: "en",
        original_title: "Godzilla vs. Kong",
        overview:
          "In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.",
        popularity: 3242.331,
        poster_path: "/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg",
        release_date: "2021-03-24",
        title: "Godzilla vs. Kong",
        video: false,
        vote_average: 8.2,
        vote_count: 5071,
      },
      {
        adult: false,
        backdrop_path: "/zDq2pwPyt4xwSFHKUoNN2LohDWj.jpg",
        genre_ids: [27],
        id: 632357,
        original_language: "en",
        original_title: "The Unholy",
        overview:
          "Alice, a young hearing-impaired girl who, after a supposed visitation from the Virgin Mary, is inexplicably able to hear, speak and heal the sick. As word spreads and people from near and far flock to witness her miracles, a disgraced journalist hoping to revive his career visits the small New England town to investigate. When terrifying events begin to happen all around, he starts to question if these phenomena are the works of the Virgin Mary or something much more sinister.",
        popularity: 2248.732,
        poster_path: "/b4gYVcl8pParX8AjkN90iQrWrWO.jpg",
        release_date: "2021-03-31",
        title: "The Unholy",
        video: false,
        vote_average: 5.7,
        vote_count: 56,
      },
      {
        adult: false,
        backdrop_path: "/6zbKgwgaaCyyBXE4Sun4oWQfQmi.jpg",
        genre_ids: [28, 53, 80],
        id: 615457,
        original_language: "en",
        original_title: "Nobody",
        overview:
          'Hutch Mansell, a suburban dad, overlooked husband, nothing neighbor — a "nobody." When two thieves break into his home one night, Hutch\'s unknown long-simmering rage is ignited and propels him on a brutal path that will uncover dark secrets he fought to leave behind.',
        popularity: 2130.016,
        poster_path: "/oBgWY00bEFeZ9N25wWVyuQddbAo.jpg",
        release_date: "2021-03-18",
        title: "Nobody",
        video: false,
        vote_average: 8.5,
        vote_count: 946,
      },
      {
        adult: false,
        backdrop_path: "/pcDc2WJAYGJTTvRSEIpRZwM3Ola.jpg",
        genre_ids: [28, 12, 14, 878],
        id: 791373,
        original_language: "en",
        original_title: "Zack Snyder's Justice League",
        overview:
          "Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.",
        popularity: 1957.088,
        poster_path: "/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg",
        release_date: "2021-03-18",
        title: "Zack Snyder's Justice League",
        video: false,
        vote_average: 8.5,
        vote_count: 5213,
      },
      {
        adult: false,
        backdrop_path: "/5Zv5KmgZzdIvXz2KC3n0MyecSNL.jpg",
        genre_ids: [28, 53, 80],
        id: 634528,
        original_language: "en",
        original_title: "The Marksman",
        overview:
          "Jim Hanson’s quiet life is suddenly disturbed by two people crossing the US/Mexico border – a woman and her young son – desperate to flee a Mexican cartel. After a shootout leaves the mother dead, Jim becomes the boy’s reluctant defender. He embraces his role as Miguel’s protector and will stop at nothing to get him to safety, as they go on the run from the relentless assassins.",
        popularity: 1944.29,
        poster_path: "/6vcDalR50RWa309vBH1NLmG2rjQ.jpg",
        release_date: "2021-01-15",
        title: "The Marksman",
        video: false,
        vote_average: 7.4,
        vote_count: 264,
      },
      {
        adult: false,
        backdrop_path: "/3FVe3OAdgz060JaxIAaUl5lo6cx.jpg",
        genre_ids: [16, 28, 12, 14, 18],
        id: 635302,
        original_language: "ja",
        original_title: "劇場版「鬼滅の刃」無限列車編",
        overview:
          "Tanjiro Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyojuro Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!",
        popularity: 2587.514,
        poster_path: "/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg",
        release_date: "2020-10-16",
        title: "Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train",
        video: false,
        vote_average: 8.2,
        vote_count: 695,
      },
      {
        adult: false,
        backdrop_path: "/z7HLq35df6ZpRxdMAE0qE3Ge4SJ.jpg",
        genre_ids: [28, 12, 35, 14],
        id: 615678,
        original_language: "en",
        original_title: "Thunder Force",
        overview:
          "In a world where supervillains are commonplace, two estranged childhood best friends reunite after one devises a treatment that gives them powers to protect their city.",
        popularity: 1768.203,
        poster_path: "/duK11VQd4UPDa7UJrgrGx90xJOx.jpg",
        release_date: "2021-04-09",
        title: "Thunder Force",
        video: false,
        vote_average: 5.8,
        vote_count: 464,
      },
      {
        adult: false,
        backdrop_path: "/ovggmAOu1IbPGTQE8lg4lBasNC7.jpg",
        genre_ids: [878, 28, 12, 53],
        id: 412656,
        original_language: "en",
        original_title: "Chaos Walking",
        overview:
          "Two unlikely companions embark on a perilous adventure through the badlands of an unexplored planet as they try to escape a dangerous and disorienting reality, where all inner thoughts are seen and heard by everyone.",
        popularity: 1362.904,
        poster_path: "/9kg73Mg8WJKlB9Y2SAJzeDKAnuB.jpg",
        release_date: "2021-02-24",
        title: "Chaos Walking",
        video: false,
        vote_average: 7.3,
        vote_count: 480,
      },
      {
        adult: false,
        backdrop_path: "/mb3fcmQzXd8aUf7r6izZfMHSJmz.jpg",
        genre_ids: [28, 80, 53],
        id: 804435,
        original_language: "en",
        original_title: "Vanquish",
        overview:
          "Victoria is a young mother trying to put her dark past as a Russian drug courier behind her, but retired cop Damon forces Victoria to do his bidding by holding her daughter hostage. Now, Victoria must use guns, guts and a motorcycle to take out a series of violent gangsters—or she may never see her child again.",
        popularity: 1854.39,
        poster_path: "/AoWY1gkcNzabh229Icboa1Ff0BM.jpg",
        release_date: "2021-04-16",
        title: "Vanquish",
        video: false,
        vote_average: 6.2,
        vote_count: 42,
      },
      {
        adult: false,
        backdrop_path: "/7prYzufdIOy1KCTZKVWpjBFqqNr.jpg",
        genre_ids: [16, 12, 14, 10751, 28],
        id: 527774,
        original_language: "en",
        original_title: "Raya and the Last Dragon",
        overview:
          "Long ago, in the fantasy world of Kumandra, humans and dragons lived together in harmony. But when an evil force threatened the land, the dragons sacrificed themselves to save humanity. Now, 500 years later, that same evil has returned and it’s up to a lone warrior, Raya, to track down the legendary last dragon to restore the fractured land and its divided people.",
        popularity: 1286.989,
        poster_path: "/lPsD10PP4rgUGiGR4CCXA6iY0QQ.jpg",
        release_date: "2021-03-03",
        title: "Raya and the Last Dragon",
        video: false,
        vote_average: 8.3,
        vote_count: 2516,
      },
      {
        adult: false,
        backdrop_path: "/lHhc60NXYzswU4TvKSo45nY9Jzs.jpg",
        genre_ids: [16, 35, 10751, 12],
        id: 726684,
        original_language: "fr",
        original_title: "Miraculous World Shanghai, la légende de Ladydragon",
        overview:
          "To join Adrien in Shanghai, Marinette is going to visit her uncle Wang who is celebrating his anniversary. But, as soon as she arrives in China, her purse gets stolen with Tikki inside, whom she needs to secretly transform into Ladybug! Without money and alone in the immense city, Marinette accepts the help of a young and resourceful girl, Fei. The two girls will ally and discover the existence of a new magical jewel, the Prodigious. Hawk Moth, also present in Shanghai, seeks to finding it since a long time...",
        popularity: 1509.953,
        poster_path: "/msI5a9TPnepx47JUb2vl88hb80R.jpg",
        release_date: "2021-04-04",
        title: "Miraculous World: Shanghai – The Legend of Ladydragon",
        video: false,
        vote_average: 7.8,
        vote_count: 212,
      },
      {
        adult: false,
        backdrop_path: "/z8TvnEVRenMSTemxYZwLGqFofgF.jpg",
        genre_ids: [14, 28, 12],
        id: 458576,
        original_language: "en",
        original_title: "Monster Hunter",
        overview:
          "A portal transports Cpt. Artemis and an elite unit of soldiers to a strange world where powerful monsters rule with deadly ferocity. Faced with relentless danger, the team encounters a mysterious hunter who may be their only hope to find a way home.",
        popularity: 948.261,
        poster_path: "/1UCOF11QCw8kcqvce8LKOO6pimh.jpg",
        release_date: "2020-12-03",
        title: "Monster Hunter",
        video: false,
        vote_average: 7.1,
        vote_count: 1546,
      },
      {
        adult: false,
        backdrop_path: "/y0SiXoTLQp93NbLQ4XhgVz18UAS.jpg",
        genre_ids: [16, 28, 14],
        id: 663558,
        original_language: "zh",
        original_title: "新神榜：哪吒重生",
        overview:
          "3000 years after the boy-god Nezha conquers the Dragon King then disappears in mythological times, he returns as an ordinary man to find his own path to becoming a true hero.",
        popularity: 891.488,
        poster_path: "/6goDkAD6J3br81YMQf0Gat8Bqjy.jpg",
        release_date: "2021-02-06",
        title: "New Gods: Nezha Reborn",
        video: false,
        vote_average: 8.9,
        vote_count: 113,
      },
      {
        adult: false,
        backdrop_path: "/srYya1ZlI97Au4jUYAktDe3avyA.jpg",
        genre_ids: [14, 28, 12],
        id: 464052,
        original_language: "en",
        original_title: "Wonder Woman 1984",
        overview:
          "A botched store robbery places Wonder Woman in a global battle against a powerful and mysterious ancient force that puts her powers in jeopardy.",
        popularity: 917.647,
        poster_path: "/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
        release_date: "2020-12-16",
        title: "Wonder Woman 1984",
        video: false,
        vote_average: 6.8,
        vote_count: 4985,
      },
      {
        adult: false,
        backdrop_path: "/9xeEGUZjgiKlI69jwIOi0hjKUIk.jpg",
        genre_ids: [16, 28, 14],
        id: 664767,
        original_language: "en",
        original_title: "Mortal Kombat Legends: Scorpion's Revenge",
        overview:
          "After the vicious slaughter of his family by stone-cold mercenary Sub-Zero, Hanzo Hasashi is exiled to the torturous Netherrealm. There, in exchange for his servitude to the sinister Quan Chi, he’s given a chance to avenge his family – and is resurrected as Scorpion, a lost soul bent on revenge. Back on Earthrealm, Lord Raiden gathers a team of elite warriors – Shaolin monk Liu Kang, Special Forces officer Sonya Blade and action star Johnny Cage – an unlikely band of heroes with one chance to save humanity. To do this, they must defeat Shang Tsung’s horde of Outworld gladiators and reign over the Mortal Kombat tournament.",
        popularity: 853.606,
        poster_path: "/4VlXER3FImHeFuUjBShFamhIp9M.jpg",
        release_date: "2020-04-12",
        title: "Mortal Kombat Legends: Scorpion's Revenge",
        video: false,
        vote_average: 8.4,
        vote_count: 887,
      },
      {
        adult: false,
        backdrop_path: "/fev8UFNFFYsD5q7AcYS8LyTzqwl.jpg",
        genre_ids: [35, 10751, 16],
        id: 587807,
        original_language: "en",
        original_title: "Tom & Jerry",
        overview:
          "Tom the cat and Jerry the mouse get kicked out of their home and relocate to a fancy New York hotel, where a scrappy employee named Kayla will lose her job if she can’t evict Jerry before a high-class wedding at the hotel. Her solution? Hiring Tom to get rid of the pesky mouse.",
        popularity: 848.504,
        poster_path: "/6KErczPBROQty7QoIsaa6wJYXZi.jpg",
        release_date: "2021-02-11",
        title: "Tom & Jerry",
        video: false,
        vote_average: 7.3,
        vote_count: 1255,
      },
      {
        adult: false,
        backdrop_path: "/d6AppFOLRLy98JvCz5N8YD40XEl.jpg",
        genre_ids: [27],
        id: 791910,
        original_language: "en",
        original_title: "Rise of the Mummy",
        overview:
          "A group of archaeology students awaken an ancient mummy. After being trapped in a time loop, the only way they can escape, is to defeat the mummy. As the body count rises, it seems the Mummy has to collect the souls of those who woke him to be able to walk the earth - for good.",
        popularity: 670.127,
        poster_path: "/tmghT8HaddVIS9hEXIOI9GuDchi.jpg",
        release_date: "2021-04-03",
        title: "Rise of the Mummy",
        video: false,
        vote_average: 5,
        vote_count: 11,
      },
      {
        adult: false,
        backdrop_path: "/gzJnMEMkHowkUndn9gCr8ghQPzN.jpg",
        genre_ids: [53, 28, 18],
        id: 793723,
        original_language: "fr",
        original_title: "Sentinelle",
        overview:
          "Transferred home after a traumatizing combat mission, a highly trained French soldier uses her lethal skills to hunt down the man who hurt her sister.",
        popularity: 780.643,
        poster_path: "/fFRq98cW9lTo6di2o4lK1qUAWaN.jpg",
        release_date: "2021-03-05",
        title: "Sentinelle",
        video: false,
        vote_average: 6,
        vote_count: 354,
      },
      {
        adult: false,
        backdrop_path: "/uQtqiAu2bBlokqjlURVLEha6zoi.jpg",
        genre_ids: [80, 18],
        id: 544401,
        original_language: "en",
        original_title: "Cherry",
        overview:
          "Cherry drifts from college dropout to army medic in Iraq - anchored only by his true love, Emily. But after returning from the war with PTSD, his life spirals into drugs and crime as he struggles to find his place in the world.",
        popularity: 771.1,
        poster_path: "/pwDvkDyaHEU9V7cApQhbcSJMG1w.jpg",
        release_date: "2021-02-26",
        title: "Cherry",
        video: false,
        vote_average: 7.6,
        vote_count: 547,
      },
    ],
    total_pages: 500,
    total_results: 10000,
  },
  status: 200,
  statusText: "",
  headers: {
    "cache-control": "public, max-age=600",
    "content-type": "application/json;charset=utf-8",
  },
  config: {
    url:
      "/discover/movie?api_key=998fbc8cc4dcef8db8fe2fd268686191&with_networks=213",
    method: "get",
    headers: { Accept: "application/json, text/plain, */*" },
    baseURL: "https://api.themoviedb.org/3",
    transformRequest: [null],
    transformResponse: [null],
    timeout: 0,
    xsrfCookieName: "XSRF-TOKEN",
    xsrfHeaderName: "X-XSRF-TOKEN",
    maxContentLength: -1,
    maxBodyLength: -1,
  },
  request: {},
};
