export const requests = {
  NetflixOriginals: {
    data: {
      page: 1,
      results: [
        {
          adult: false,
          backdrop_path: "/9yBVqNruk6Ykrwc32qrK2TIE5xw.jpg",
          genre_ids: [14, 28, 12, 878, 53],
          id: 460465,
          original_language: "en",
          original_title: "Mortal Kombat",
          overview:
            "Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung's best warrior, Sub-Zero, seeks out and trains with Earth's greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.",
          popularity: 7966.615,
          poster_path: "/6Wdl9N6dL0Hi0T1qJLWSz6gMLbd.jpg",
          release_date: "2021-04-07",
          title: "Mortal Kombat",
          video: false,
          vote_average: 7.9,
          vote_count: 1747,
        },
        {
          adult: false,
          backdrop_path: "/inJjDhCjfhh3RtrJWBmmDqeuSYC.jpg",
          genre_ids: [878, 28],
          id: 399566,
          original_language: "en",
          original_title: "Godzilla vs. Kong",
          overview:
            "In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.",
          popularity: 3242.331,
          poster_path: "/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg",
          release_date: "2021-03-24",
          title: "Godzilla vs. Kong",
          video: false,
          vote_average: 8.2,
          vote_count: 5071,
        },
        {
          adult: false,
          backdrop_path: "/zDq2pwPyt4xwSFHKUoNN2LohDWj.jpg",
          genre_ids: [27],
          id: 632357,
          original_language: "en",
          original_title: "The Unholy",
          overview:
            "Alice, a young hearing-impaired girl who, after a supposed visitation from the Virgin Mary, is inexplicably able to hear, speak and heal the sick. As word spreads and people from near and far flock to witness her miracles, a disgraced journalist hoping to revive his career visits the small New England town to investigate. When terrifying events begin to happen all around, he starts to question if these phenomena are the works of the Virgin Mary or something much more sinister.",
          popularity: 2248.732,
          poster_path: "/b4gYVcl8pParX8AjkN90iQrWrWO.jpg",
          release_date: "2021-03-31",
          title: "The Unholy",
          video: false,
          vote_average: 5.7,
          vote_count: 56,
        },
        {
          adult: false,
          backdrop_path: "/6zbKgwgaaCyyBXE4Sun4oWQfQmi.jpg",
          genre_ids: [28, 53, 80],
          id: 615457,
          original_language: "en",
          original_title: "Nobody",
          overview:
            'Hutch Mansell, a suburban dad, overlooked husband, nothing neighbor — a "nobody." When two thieves break into his home one night, Hutch\'s unknown long-simmering rage is ignited and propels him on a brutal path that will uncover dark secrets he fought to leave behind.',
          popularity: 2130.016,
          poster_path: "/oBgWY00bEFeZ9N25wWVyuQddbAo.jpg",
          release_date: "2021-03-18",
          title: "Nobody",
          video: false,
          vote_average: 8.5,
          vote_count: 946,
        },
        {
          adult: false,
          backdrop_path: "/pcDc2WJAYGJTTvRSEIpRZwM3Ola.jpg",
          genre_ids: [28, 12, 14, 878],
          id: 791373,
          original_language: "en",
          original_title: "Zack Snyder's Justice League",
          overview:
            "Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.",
          popularity: 1957.088,
          poster_path: "/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg",
          release_date: "2021-03-18",
          title: "Zack Snyder's Justice League",
          video: false,
          vote_average: 8.5,
          vote_count: 5213,
        },
        {
          adult: false,
          backdrop_path: "/5Zv5KmgZzdIvXz2KC3n0MyecSNL.jpg",
          genre_ids: [28, 53, 80],
          id: 634528,
          original_language: "en",
          original_title: "The Marksman",
          overview:
            "Jim Hanson’s quiet life is suddenly disturbed by two people crossing the US/Mexico border – a woman and her young son – desperate to flee a Mexican cartel. After a shootout leaves the mother dead, Jim becomes the boy’s reluctant defender. He embraces his role as Miguel’s protector and will stop at nothing to get him to safety, as they go on the run from the relentless assassins.",
          popularity: 1944.29,
          poster_path: "/6vcDalR50RWa309vBH1NLmG2rjQ.jpg",
          release_date: "2021-01-15",
          title: "The Marksman",
          video: false,
          vote_average: 7.4,
          vote_count: 264,
        },
        {
          adult: false,
          backdrop_path: "/3FVe3OAdgz060JaxIAaUl5lo6cx.jpg",
          genre_ids: [16, 28, 12, 14, 18],
          id: 635302,
          original_language: "ja",
          original_title: "劇場版「鬼滅の刃」無限列車編",
          overview:
            "Tanjiro Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyojuro Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!",
          popularity: 2587.514,
          poster_path: "/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg",
          release_date: "2020-10-16",
          title: "Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train",
          video: false,
          vote_average: 8.2,
          vote_count: 695,
        },
        {
          adult: false,
          backdrop_path: "/z7HLq35df6ZpRxdMAE0qE3Ge4SJ.jpg",
          genre_ids: [28, 12, 35, 14],
          id: 615678,
          original_language: "en",
          original_title: "Thunder Force",
          overview:
            "In a world where supervillains are commonplace, two estranged childhood best friends reunite after one devises a treatment that gives them powers to protect their city.",
          popularity: 1768.203,
          poster_path: "/duK11VQd4UPDa7UJrgrGx90xJOx.jpg",
          release_date: "2021-04-09",
          title: "Thunder Force",
          video: false,
          vote_average: 5.8,
          vote_count: 464,
        },
        {
          adult: false,
          backdrop_path: "/ovggmAOu1IbPGTQE8lg4lBasNC7.jpg",
          genre_ids: [878, 28, 12, 53],
          id: 412656,
          original_language: "en",
          original_title: "Chaos Walking",
          overview:
            "Two unlikely companions embark on a perilous adventure through the badlands of an unexplored planet as they try to escape a dangerous and disorienting reality, where all inner thoughts are seen and heard by everyone.",
          popularity: 1362.904,
          poster_path: "/9kg73Mg8WJKlB9Y2SAJzeDKAnuB.jpg",
          release_date: "2021-02-24",
          title: "Chaos Walking",
          video: false,
          vote_average: 7.3,
          vote_count: 480,
        },
        {
          adult: false,
          backdrop_path: "/mb3fcmQzXd8aUf7r6izZfMHSJmz.jpg",
          genre_ids: [28, 80, 53],
          id: 804435,
          original_language: "en",
          original_title: "Vanquish",
          overview:
            "Victoria is a young mother trying to put her dark past as a Russian drug courier behind her, but retired cop Damon forces Victoria to do his bidding by holding her daughter hostage. Now, Victoria must use guns, guts and a motorcycle to take out a series of violent gangsters—or she may never see her child again.",
          popularity: 1854.39,
          poster_path: "/AoWY1gkcNzabh229Icboa1Ff0BM.jpg",
          release_date: "2021-04-16",
          title: "Vanquish",
          video: false,
          vote_average: 6.2,
          vote_count: 42,
        },
        {
          adult: false,
          backdrop_path: "/7prYzufdIOy1KCTZKVWpjBFqqNr.jpg",
          genre_ids: [16, 12, 14, 10751, 28],
          id: 527774,
          original_language: "en",
          original_title: "Raya and the Last Dragon",
          overview:
            "Long ago, in the fantasy world of Kumandra, humans and dragons lived together in harmony. But when an evil force threatened the land, the dragons sacrificed themselves to save humanity. Now, 500 years later, that same evil has returned and it’s up to a lone warrior, Raya, to track down the legendary last dragon to restore the fractured land and its divided people.",
          popularity: 1286.989,
          poster_path: "/lPsD10PP4rgUGiGR4CCXA6iY0QQ.jpg",
          release_date: "2021-03-03",
          title: "Raya and the Last Dragon",
          video: false,
          vote_average: 8.3,
          vote_count: 2516,
        },
        {
          adult: false,
          backdrop_path: "/lHhc60NXYzswU4TvKSo45nY9Jzs.jpg",
          genre_ids: [16, 35, 10751, 12],
          id: 726684,
          original_language: "fr",
          original_title: "Miraculous World Shanghai, la légende de Ladydragon",
          overview:
            "To join Adrien in Shanghai, Marinette is going to visit her uncle Wang who is celebrating his anniversary. But, as soon as she arrives in China, her purse gets stolen with Tikki inside, whom she needs to secretly transform into Ladybug! Without money and alone in the immense city, Marinette accepts the help of a young and resourceful girl, Fei. The two girls will ally and discover the existence of a new magical jewel, the Prodigious. Hawk Moth, also present in Shanghai, seeks to finding it since a long time...",
          popularity: 1509.953,
          poster_path: "/msI5a9TPnepx47JUb2vl88hb80R.jpg",
          release_date: "2021-04-04",
          title: "Miraculous World: Shanghai – The Legend of Ladydragon",
          video: false,
          vote_average: 7.8,
          vote_count: 212,
        },
        {
          adult: false,
          backdrop_path: "/z8TvnEVRenMSTemxYZwLGqFofgF.jpg",
          genre_ids: [14, 28, 12],
          id: 458576,
          original_language: "en",
          original_title: "Monster Hunter",
          overview:
            "A portal transports Cpt. Artemis and an elite unit of soldiers to a strange world where powerful monsters rule with deadly ferocity. Faced with relentless danger, the team encounters a mysterious hunter who may be their only hope to find a way home.",
          popularity: 948.261,
          poster_path: "/1UCOF11QCw8kcqvce8LKOO6pimh.jpg",
          release_date: "2020-12-03",
          title: "Monster Hunter",
          video: false,
          vote_average: 7.1,
          vote_count: 1546,
        },
        {
          adult: false,
          backdrop_path: "/y0SiXoTLQp93NbLQ4XhgVz18UAS.jpg",
          genre_ids: [16, 28, 14],
          id: 663558,
          original_language: "zh",
          original_title: "新神榜：哪吒重生",
          overview:
            "3000 years after the boy-god Nezha conquers the Dragon King then disappears in mythological times, he returns as an ordinary man to find his own path to becoming a true hero.",
          popularity: 891.488,
          poster_path: "/6goDkAD6J3br81YMQf0Gat8Bqjy.jpg",
          release_date: "2021-02-06",
          title: "New Gods: Nezha Reborn",
          video: false,
          vote_average: 8.9,
          vote_count: 113,
        },
        {
          adult: false,
          backdrop_path: "/srYya1ZlI97Au4jUYAktDe3avyA.jpg",
          genre_ids: [14, 28, 12],
          id: 464052,
          original_language: "en",
          original_title: "Wonder Woman 1984",
          overview:
            "A botched store robbery places Wonder Woman in a global battle against a powerful and mysterious ancient force that puts her powers in jeopardy.",
          popularity: 917.647,
          poster_path: "/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
          release_date: "2020-12-16",
          title: "Wonder Woman 1984",
          video: false,
          vote_average: 6.8,
          vote_count: 4985,
        },
        {
          adult: false,
          backdrop_path: "/9xeEGUZjgiKlI69jwIOi0hjKUIk.jpg",
          genre_ids: [16, 28, 14],
          id: 664767,
          original_language: "en",
          original_title: "Mortal Kombat Legends: Scorpion's Revenge",
          overview:
            "After the vicious slaughter of his family by stone-cold mercenary Sub-Zero, Hanzo Hasashi is exiled to the torturous Netherrealm. There, in exchange for his servitude to the sinister Quan Chi, he’s given a chance to avenge his family – and is resurrected as Scorpion, a lost soul bent on revenge. Back on Earthrealm, Lord Raiden gathers a team of elite warriors – Shaolin monk Liu Kang, Special Forces officer Sonya Blade and action star Johnny Cage – an unlikely band of heroes with one chance to save humanity. To do this, they must defeat Shang Tsung’s horde of Outworld gladiators and reign over the Mortal Kombat tournament.",
          popularity: 853.606,
          poster_path: "/4VlXER3FImHeFuUjBShFamhIp9M.jpg",
          release_date: "2020-04-12",
          title: "Mortal Kombat Legends: Scorpion's Revenge",
          video: false,
          vote_average: 8.4,
          vote_count: 887,
        },
        {
          adult: false,
          backdrop_path: "/fev8UFNFFYsD5q7AcYS8LyTzqwl.jpg",
          genre_ids: [35, 10751, 16],
          id: 587807,
          original_language: "en",
          original_title: "Tom & Jerry",
          overview:
            "Tom the cat and Jerry the mouse get kicked out of their home and relocate to a fancy New York hotel, where a scrappy employee named Kayla will lose her job if she can’t evict Jerry before a high-class wedding at the hotel. Her solution? Hiring Tom to get rid of the pesky mouse.",
          popularity: 848.504,
          poster_path: "/6KErczPBROQty7QoIsaa6wJYXZi.jpg",
          release_date: "2021-02-11",
          title: "Tom & Jerry",
          video: false,
          vote_average: 7.3,
          vote_count: 1255,
        },
        {
          adult: false,
          backdrop_path: "/d6AppFOLRLy98JvCz5N8YD40XEl.jpg",
          genre_ids: [27],
          id: 791910,
          original_language: "en",
          original_title: "Rise of the Mummy",
          overview:
            "A group of archaeology students awaken an ancient mummy. After being trapped in a time loop, the only way they can escape, is to defeat the mummy. As the body count rises, it seems the Mummy has to collect the souls of those who woke him to be able to walk the earth - for good.",
          popularity: 670.127,
          poster_path: "/tmghT8HaddVIS9hEXIOI9GuDchi.jpg",
          release_date: "2021-04-03",
          title: "Rise of the Mummy",
          video: false,
          vote_average: 5,
          vote_count: 11,
        },
        {
          adult: false,
          backdrop_path: "/gzJnMEMkHowkUndn9gCr8ghQPzN.jpg",
          genre_ids: [53, 28, 18],
          id: 793723,
          original_language: "fr",
          original_title: "Sentinelle",
          overview:
            "Transferred home after a traumatizing combat mission, a highly trained French soldier uses her lethal skills to hunt down the man who hurt her sister.",
          popularity: 780.643,
          poster_path: "/fFRq98cW9lTo6di2o4lK1qUAWaN.jpg",
          release_date: "2021-03-05",
          title: "Sentinelle",
          video: false,
          vote_average: 6,
          vote_count: 354,
        },
        {
          adult: false,
          backdrop_path: "/uQtqiAu2bBlokqjlURVLEha6zoi.jpg",
          genre_ids: [80, 18],
          id: 544401,
          original_language: "en",
          original_title: "Cherry",
          overview:
            "Cherry drifts from college dropout to army medic in Iraq - anchored only by his true love, Emily. But after returning from the war with PTSD, his life spirals into drugs and crime as he struggles to find his place in the world.",
          popularity: 771.1,
          poster_path: "/pwDvkDyaHEU9V7cApQhbcSJMG1w.jpg",
          release_date: "2021-02-26",
          title: "Cherry",
          video: false,
          vote_average: 7.6,
          vote_count: 547,
        },
      ],
      total_pages: 500,
      total_results: 10000,
    },
    status: 200,
    statusText: "",
    headers: {
      "cache-control": "public, max-age=600",
      "content-type": "application/json;charset=utf-8",
    },
    config: {
      url:
        "/discover/movie?api_key=998fbc8cc4dcef8db8fe2fd268686191&with_networks=213",
      method: "get",
      headers: { Accept: "application/json, text/plain, */*" },
      baseURL: "https://api.themoviedb.org/3",
      transformRequest: [null],
      transformResponse: [null],
      timeout: 0,
      xsrfCookieName: "XSRF-TOKEN",
      xsrfHeaderName: "X-XSRF-TOKEN",
      maxContentLength: -1,
      maxBodyLength: -1,
    },
    request: {},
  },
  AnimeMovies: {
    data: {
      page: 1,
      results: [
        {
          adult: false,
          backdrop_path: "/9yBVqNruk6Ykrwc32qrK2TIE5xw.jpg",
          genre_ids: [14, 28, 12, 878, 53],
          id: 460465,
          original_language: "en",
          original_title: "Mortal Kombat",
          overview:
            "Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung's best warrior, Sub-Zero, seeks out and trains with Earth's greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.",
          popularity: 7966.615,
          poster_path: "/6Wdl9N6dL0Hi0T1qJLWSz6gMLbd.jpg",
          release_date: "2021-04-07",
          title: "Mortal Kombat",
          video: false,
          vote_average: 7.9,
          vote_count: 1747,
        },
        {
          adult: false,
          backdrop_path: "/inJjDhCjfhh3RtrJWBmmDqeuSYC.jpg",
          genre_ids: [878, 28],
          id: 399566,
          original_language: "en",
          original_title: "Godzilla vs. Kong",
          overview:
            "In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.",
          popularity: 3242.331,
          poster_path: "/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg",
          release_date: "2021-03-24",
          title: "Godzilla vs. Kong",
          video: false,
          vote_average: 8.2,
          vote_count: 5071,
        },
        {
          adult: false,
          backdrop_path: "/zDq2pwPyt4xwSFHKUoNN2LohDWj.jpg",
          genre_ids: [27],
          id: 632357,
          original_language: "en",
          original_title: "The Unholy",
          overview:
            "Alice, a young hearing-impaired girl who, after a supposed visitation from the Virgin Mary, is inexplicably able to hear, speak and heal the sick. As word spreads and people from near and far flock to witness her miracles, a disgraced journalist hoping to revive his career visits the small New England town to investigate. When terrifying events begin to happen all around, he starts to question if these phenomena are the works of the Virgin Mary or something much more sinister.",
          popularity: 2248.732,
          poster_path: "/b4gYVcl8pParX8AjkN90iQrWrWO.jpg",
          release_date: "2021-03-31",
          title: "The Unholy",
          video: false,
          vote_average: 5.7,
          vote_count: 56,
        },
        {
          adult: false,
          backdrop_path: "/6zbKgwgaaCyyBXE4Sun4oWQfQmi.jpg",
          genre_ids: [28, 53, 80],
          id: 615457,
          original_language: "en",
          original_title: "Nobody",
          overview:
            'Hutch Mansell, a suburban dad, overlooked husband, nothing neighbor — a "nobody." When two thieves break into his home one night, Hutch\'s unknown long-simmering rage is ignited and propels him on a brutal path that will uncover dark secrets he fought to leave behind.',
          popularity: 2130.016,
          poster_path: "/oBgWY00bEFeZ9N25wWVyuQddbAo.jpg",
          release_date: "2021-03-18",
          title: "Nobody",
          video: false,
          vote_average: 8.5,
          vote_count: 946,
        },
        {
          adult: false,
          backdrop_path: "/pcDc2WJAYGJTTvRSEIpRZwM3Ola.jpg",
          genre_ids: [28, 12, 14, 878],
          id: 791373,
          original_language: "en",
          original_title: "Zack Snyder's Justice League",
          overview:
            "Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.",
          popularity: 1957.088,
          poster_path: "/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg",
          release_date: "2021-03-18",
          title: "Zack Snyder's Justice League",
          video: false,
          vote_average: 8.5,
          vote_count: 5213,
        },
        {
          adult: false,
          backdrop_path: "/5Zv5KmgZzdIvXz2KC3n0MyecSNL.jpg",
          genre_ids: [28, 53, 80],
          id: 634528,
          original_language: "en",
          original_title: "The Marksman",
          overview:
            "Jim Hanson’s quiet life is suddenly disturbed by two people crossing the US/Mexico border – a woman and her young son – desperate to flee a Mexican cartel. After a shootout leaves the mother dead, Jim becomes the boy’s reluctant defender. He embraces his role as Miguel’s protector and will stop at nothing to get him to safety, as they go on the run from the relentless assassins.",
          popularity: 1944.29,
          poster_path: "/6vcDalR50RWa309vBH1NLmG2rjQ.jpg",
          release_date: "2021-01-15",
          title: "The Marksman",
          video: false,
          vote_average: 7.4,
          vote_count: 264,
        },
        {
          adult: false,
          backdrop_path: "/3FVe3OAdgz060JaxIAaUl5lo6cx.jpg",
          genre_ids: [16, 28, 12, 14, 18],
          id: 635302,
          original_language: "ja",
          original_title: "劇場版「鬼滅の刃」無限列車編",
          overview:
            "Tanjiro Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyojuro Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!",
          popularity: 2587.514,
          poster_path: "/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg",
          release_date: "2020-10-16",
          title: "Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train",
          video: false,
          vote_average: 8.2,
          vote_count: 695,
        },
        {
          adult: false,
          backdrop_path: "/z7HLq35df6ZpRxdMAE0qE3Ge4SJ.jpg",
          genre_ids: [28, 12, 35, 14],
          id: 615678,
          original_language: "en",
          original_title: "Thunder Force",
          overview:
            "In a world where supervillains are commonplace, two estranged childhood best friends reunite after one devises a treatment that gives them powers to protect their city.",
          popularity: 1768.203,
          poster_path: "/duK11VQd4UPDa7UJrgrGx90xJOx.jpg",
          release_date: "2021-04-09",
          title: "Thunder Force",
          video: false,
          vote_average: 5.8,
          vote_count: 464,
        },
        {
          adult: false,
          backdrop_path: "/ovggmAOu1IbPGTQE8lg4lBasNC7.jpg",
          genre_ids: [878, 28, 12, 53],
          id: 412656,
          original_language: "en",
          original_title: "Chaos Walking",
          overview:
            "Two unlikely companions embark on a perilous adventure through the badlands of an unexplored planet as they try to escape a dangerous and disorienting reality, where all inner thoughts are seen and heard by everyone.",
          popularity: 1362.904,
          poster_path: "/9kg73Mg8WJKlB9Y2SAJzeDKAnuB.jpg",
          release_date: "2021-02-24",
          title: "Chaos Walking",
          video: false,
          vote_average: 7.3,
          vote_count: 480,
        },
        {
          adult: false,
          backdrop_path: "/mb3fcmQzXd8aUf7r6izZfMHSJmz.jpg",
          genre_ids: [28, 80, 53],
          id: 804435,
          original_language: "en",
          original_title: "Vanquish",
          overview:
            "Victoria is a young mother trying to put her dark past as a Russian drug courier behind her, but retired cop Damon forces Victoria to do his bidding by holding her daughter hostage. Now, Victoria must use guns, guts and a motorcycle to take out a series of violent gangsters—or she may never see her child again.",
          popularity: 1854.39,
          poster_path: "/AoWY1gkcNzabh229Icboa1Ff0BM.jpg",
          release_date: "2021-04-16",
          title: "Vanquish",
          video: false,
          vote_average: 6.2,
          vote_count: 42,
        },
        {
          adult: false,
          backdrop_path: "/7prYzufdIOy1KCTZKVWpjBFqqNr.jpg",
          genre_ids: [16, 12, 14, 10751, 28],
          id: 527774,
          original_language: "en",
          original_title: "Raya and the Last Dragon",
          overview:
            "Long ago, in the fantasy world of Kumandra, humans and dragons lived together in harmony. But when an evil force threatened the land, the dragons sacrificed themselves to save humanity. Now, 500 years later, that same evil has returned and it’s up to a lone warrior, Raya, to track down the legendary last dragon to restore the fractured land and its divided people.",
          popularity: 1286.989,
          poster_path: "/lPsD10PP4rgUGiGR4CCXA6iY0QQ.jpg",
          release_date: "2021-03-03",
          title: "Raya and the Last Dragon",
          video: false,
          vote_average: 8.3,
          vote_count: 2516,
        },
        {
          adult: false,
          backdrop_path: "/lHhc60NXYzswU4TvKSo45nY9Jzs.jpg",
          genre_ids: [16, 35, 10751, 12],
          id: 726684,
          original_language: "fr",
          original_title: "Miraculous World Shanghai, la légende de Ladydragon",
          overview:
            "To join Adrien in Shanghai, Marinette is going to visit her uncle Wang who is celebrating his anniversary. But, as soon as she arrives in China, her purse gets stolen with Tikki inside, whom she needs to secretly transform into Ladybug! Without money and alone in the immense city, Marinette accepts the help of a young and resourceful girl, Fei. The two girls will ally and discover the existence of a new magical jewel, the Prodigious. Hawk Moth, also present in Shanghai, seeks to finding it since a long time...",
          popularity: 1509.953,
          poster_path: "/msI5a9TPnepx47JUb2vl88hb80R.jpg",
          release_date: "2021-04-04",
          title: "Miraculous World: Shanghai – The Legend of Ladydragon",
          video: false,
          vote_average: 7.8,
          vote_count: 212,
        },
        {
          adult: false,
          backdrop_path: "/z8TvnEVRenMSTemxYZwLGqFofgF.jpg",
          genre_ids: [14, 28, 12],
          id: 458576,
          original_language: "en",
          original_title: "Monster Hunter",
          overview:
            "A portal transports Cpt. Artemis and an elite unit of soldiers to a strange world where powerful monsters rule with deadly ferocity. Faced with relentless danger, the team encounters a mysterious hunter who may be their only hope to find a way home.",
          popularity: 948.261,
          poster_path: "/1UCOF11QCw8kcqvce8LKOO6pimh.jpg",
          release_date: "2020-12-03",
          title: "Monster Hunter",
          video: false,
          vote_average: 7.1,
          vote_count: 1546,
        },
        {
          adult: false,
          backdrop_path: "/y0SiXoTLQp93NbLQ4XhgVz18UAS.jpg",
          genre_ids: [16, 28, 14],
          id: 663558,
          original_language: "zh",
          original_title: "新神榜：哪吒重生",
          overview:
            "3000 years after the boy-god Nezha conquers the Dragon King then disappears in mythological times, he returns as an ordinary man to find his own path to becoming a true hero.",
          popularity: 891.488,
          poster_path: "/6goDkAD6J3br81YMQf0Gat8Bqjy.jpg",
          release_date: "2021-02-06",
          title: "New Gods: Nezha Reborn",
          video: false,
          vote_average: 8.9,
          vote_count: 113,
        },
        {
          adult: false,
          backdrop_path: "/srYya1ZlI97Au4jUYAktDe3avyA.jpg",
          genre_ids: [14, 28, 12],
          id: 464052,
          original_language: "en",
          original_title: "Wonder Woman 1984",
          overview:
            "A botched store robbery places Wonder Woman in a global battle against a powerful and mysterious ancient force that puts her powers in jeopardy.",
          popularity: 917.647,
          poster_path: "/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
          release_date: "2020-12-16",
          title: "Wonder Woman 1984",
          video: false,
          vote_average: 6.8,
          vote_count: 4985,
        },
        {
          adult: false,
          backdrop_path: "/9xeEGUZjgiKlI69jwIOi0hjKUIk.jpg",
          genre_ids: [16, 28, 14],
          id: 664767,
          original_language: "en",
          original_title: "Mortal Kombat Legends: Scorpion's Revenge",
          overview:
            "After the vicious slaughter of his family by stone-cold mercenary Sub-Zero, Hanzo Hasashi is exiled to the torturous Netherrealm. There, in exchange for his servitude to the sinister Quan Chi, he’s given a chance to avenge his family – and is resurrected as Scorpion, a lost soul bent on revenge. Back on Earthrealm, Lord Raiden gathers a team of elite warriors – Shaolin monk Liu Kang, Special Forces officer Sonya Blade and action star Johnny Cage – an unlikely band of heroes with one chance to save humanity. To do this, they must defeat Shang Tsung’s horde of Outworld gladiators and reign over the Mortal Kombat tournament.",
          popularity: 853.606,
          poster_path: "/4VlXER3FImHeFuUjBShFamhIp9M.jpg",
          release_date: "2020-04-12",
          title: "Mortal Kombat Legends: Scorpion's Revenge",
          video: false,
          vote_average: 8.4,
          vote_count: 887,
        },
        {
          adult: false,
          backdrop_path: "/fev8UFNFFYsD5q7AcYS8LyTzqwl.jpg",
          genre_ids: [35, 10751, 16],
          id: 587807,
          original_language: "en",
          original_title: "Tom & Jerry",
          overview:
            "Tom the cat and Jerry the mouse get kicked out of their home and relocate to a fancy New York hotel, where a scrappy employee named Kayla will lose her job if she can’t evict Jerry before a high-class wedding at the hotel. Her solution? Hiring Tom to get rid of the pesky mouse.",
          popularity: 848.504,
          poster_path: "/6KErczPBROQty7QoIsaa6wJYXZi.jpg",
          release_date: "2021-02-11",
          title: "Tom & Jerry",
          video: false,
          vote_average: 7.3,
          vote_count: 1255,
        },
        {
          adult: false,
          backdrop_path: "/d6AppFOLRLy98JvCz5N8YD40XEl.jpg",
          genre_ids: [27],
          id: 791910,
          original_language: "en",
          original_title: "Rise of the Mummy",
          overview:
            "A group of archaeology students awaken an ancient mummy. After being trapped in a time loop, the only way they can escape, is to defeat the mummy. As the body count rises, it seems the Mummy has to collect the souls of those who woke him to be able to walk the earth - for good.",
          popularity: 670.127,
          poster_path: "/tmghT8HaddVIS9hEXIOI9GuDchi.jpg",
          release_date: "2021-04-03",
          title: "Rise of the Mummy",
          video: false,
          vote_average: 5,
          vote_count: 11,
        },
        {
          adult: false,
          backdrop_path: "/gzJnMEMkHowkUndn9gCr8ghQPzN.jpg",
          genre_ids: [53, 28, 18],
          id: 793723,
          original_language: "fr",
          original_title: "Sentinelle",
          overview:
            "Transferred home after a traumatizing combat mission, a highly trained French soldier uses her lethal skills to hunt down the man who hurt her sister.",
          popularity: 780.643,
          poster_path: "/fFRq98cW9lTo6di2o4lK1qUAWaN.jpg",
          release_date: "2021-03-05",
          title: "Sentinelle",
          video: false,
          vote_average: 6,
          vote_count: 354,
        },
        {
          adult: false,
          backdrop_path: "/uQtqiAu2bBlokqjlURVLEha6zoi.jpg",
          genre_ids: [80, 18],
          id: 544401,
          original_language: "en",
          original_title: "Cherry",
          overview:
            "Cherry drifts from college dropout to army medic in Iraq - anchored only by his true love, Emily. But after returning from the war with PTSD, his life spirals into drugs and crime as he struggles to find his place in the world.",
          popularity: 771.1,
          poster_path: "/pwDvkDyaHEU9V7cApQhbcSJMG1w.jpg",
          release_date: "2021-02-26",
          title: "Cherry",
          video: false,
          vote_average: 7.6,
          vote_count: 547,
        },
      ],
      total_pages: 500,
      total_results: 10000,
    },
    status: 200,
    statusText: "",
    headers: {
      "cache-control": "public, max-age=600",
      "content-type": "application/json;charset=utf-8",
    },
    config: {
      url:
        "/discover/movie?api_key=998fbc8cc4dcef8db8fe2fd268686191&with_networks=213",
      method: "get",
      headers: { Accept: "application/json, text/plain, */*" },
      baseURL: "https://api.themoviedb.org/3",
      transformRequest: [null],
      transformResponse: [null],
      timeout: 0,
      xsrfCookieName: "XSRF-TOKEN",
      xsrfHeaderName: "X-XSRF-TOKEN",
      maxContentLength: -1,
      maxBodyLength: -1,
    },
    request: {},
  },
  RomanceMovies: {
    data: {
      page: 1,
      results: [
        {
          adult: false,
          backdrop_path: "/jw0849O7WLarbYKJkA9WpRLeGKG.jpg",
          genre_ids: [35, 10749],
          id: 802504,
          original_language: "nl",
          original_title: "Just Say Yes",
          overview:
            "Incurable romantic Lotte finds her life upended when her plans for a picture-perfect wedding unravel -- just as her self-absorbed sister gets engaged.",
          popularity: 409.451,
          poster_path: "/3btDwus5VN5jOWfA9strpDJWwfj.jpg",
          release_date: "2021-04-02",
          title: "Just Say Yes",
          video: false,
          vote_average: 5.9,
          vote_count: 77,
        },
        {
          adult: false,
          backdrop_path: "/6hgItrYQEG33y0I7yP2SRl2ei4w.jpg",
          genre_ids: [10749, 18],
          id: 613504,
          original_language: "en",
          original_title: "After We Collided",
          overview:
            "Tessa finds herself struggling with her complicated relationship with Hardin; she faces a dilemma that could change their lives forever.",
          popularity: 363.407,
          poster_path: "/kiX7UYfOpYrMFSAGbI6j1pFkLzQ.jpg",
          release_date: "2020-09-02",
          title: "After We Collided",
          video: false,
          vote_average: 7.3,
          vote_count: 3691,
        },
        {
          adult: false,
          backdrop_path: "/oCu17j8Kgaj4KnA4MH7bgQIsA7a.jpg",
          genre_ids: [18, 10749, 53],
          id: 796849,
          original_language: "ja",
          original_title: "彼女",
          overview:
            "Rei helps the woman she's been in love with for years escape her abusive husband. While on the run, their feelings for each other catch fire.",
          popularity: 306.261,
          poster_path: "/c7JzcVK4OZY1u7HYiFBOASkKPP5.jpg",
          release_date: "2021-04-15",
          title: "Ride or Die",
          video: false,
          vote_average: 6.9,
          vote_count: 44,
        },
        {
          adult: false,
          backdrop_path: "/u1wHUA0R48FH4WV3sGqjwx3aNZm.jpg",
          genre_ids: [16, 18, 10402, 10749],
          id: 632632,
          original_language: "ja",
          original_title: "映画 ギヴン",
          overview:
            "The film centers on the love relationship among the band's bassist Haruki Nakayama, drummer Akihiko Kaji, and Akihiko's roommate and ex-boyfriend Ugetsu Murata.",
          popularity: 250.587,
          poster_path: "/xKCtoYHUyX8zAg68eemnYa2orep.jpg",
          release_date: "2020-08-22",
          title: "Given",
          video: false,
          vote_average: 8.8,
          vote_count: 156,
        },
        {
          adult: false,
          backdrop_path: "/lrE4Oed7CEDfYL61twc4Pe7kPsB.jpg",
          genre_ids: [18, 10749],
          id: 802403,
          original_language: "hi",
          original_title: "अजीब दास्तान्स",
          overview:
            "An anthology of four stories that explore the surprising ways in which unexpected catalysts inflame the uncomfortable emotions simmering under fractured relationships.",
          popularity: 193.081,
          poster_path: "/5KHjF8H2bqvQdmvkmeAlFjKXkmB.jpg",
          release_date: "2021-04-16",
          title: "Ajeeb Daastaans",
          video: false,
          vote_average: 7.1,
          vote_count: 12,
        },
        {
          adult: false,
          backdrop_path: "/kzIiKLccwuzD3qD5OHFyPIkiqEw.jpg",
          genre_ids: [28, 10749, 16],
          id: 317442,
          original_language: "ja",
          original_title: "The Last: Naruto the Movie",
          overview:
            "Two years after the events of the Fourth Great Ninja War, the moon that Hagoromo Otsutsuki created long ago to seal away the Gedo Statue begins to descend towards the world, threatening to become a meteor that would destroy everything on impact. Amidst this crisis, a direct descendant of Kaguya Otsutsuki named Toneri Otsutsuki attempts to kidnap Hinata Hyuga but ends up abducting her younger sister Hanabi. Naruto and his allies now mount a rescue mission before finding themselves embroiled in a final battle to decide the fate of everything.",
          popularity: 178.493,
          poster_path: "/bAQ8O5Uw6FedtlCbJTutenzPVKd.jpg",
          release_date: "2014-12-06",
          title: "The Last: Naruto the Movie",
          video: false,
          vote_average: 7.8,
          vote_count: 907,
        },
        {
          adult: false,
          backdrop_path: "/Aw07IupDF1ubyVNrcWwDPbnCQRP.jpg",
          genre_ids: [18, 35, 10749],
          id: 583903,
          original_language: "en",
          original_title: "Our Friend",
          overview:
            "After learning that his terminally ill wife has six months to live, a man welcomes the support of his best friend who moves into their home to help out.",
          popularity: 149.175,
          poster_path: "/vg9C5LttsKBqoLuqeQvOXaeBGiD.jpg",
          release_date: "2021-01-22",
          title: "Our Friend",
          video: false,
          vote_average: 7.1,
          vote_count: 91,
        },
        {
          adult: false,
          backdrop_path: null,
          genre_ids: [10749, 18],
          id: 744275,
          original_language: "en",
          original_title: "After We Fell",
          overview:
            "Just as Tessa makes the biggest decision of her life, everything changes because of revelations about her family. Tessa's life begins to come unglued. Nothing is what she thought it was. Not her friends. Not her family. The one person she should be able to rely on, Hardin, is furious when he discovers the massive secret she's been keeping.",
          popularity: 147.22,
          poster_path: "/umy454n46930E9ak437kxT7kcXU.jpg",
          release_date: "2021-09-01",
          title: "After We Fell",
          video: false,
          vote_average: 0,
          vote_count: 0,
        },
        {
          adult: false,
          backdrop_path: "/pGTXJcZQIgqzFZlWy6KxlamlTHK.jpg",
          genre_ids: [18, 10749],
          id: 621013,
          original_language: "en",
          original_title: "Chemical Hearts",
          overview:
            "When a hopelessly romantic high school senior falls for a mysterious new classmate, it sets them both on an unexpected journey that teaches them about love, loss, and most importantly themselves.",
          popularity: 149.792,
          poster_path: "/q1MNlZYqhoD4U7sd7pjxD6SUf4z.jpg",
          release_date: "2020-08-21",
          title: "Chemical Hearts",
          video: false,
          vote_average: 7.6,
          vote_count: 785,
        },
        {
          adult: false,
          backdrop_path: "/2VnghbG2qWChcE6CdZBMDtDQKCF.jpg",
          genre_ids: [18, 10751, 10402, 10749],
          id: 699102,
          original_language: "en",
          original_title: "A Week Away",
          overview:
            "Troubled teen Will Hawkins has a run-in with the law that puts him at an important crossroad: go to juvenile detention or attend a Christian summer camp. At first a fish-out-of-water, Will opens his heart, discovers love with a camp regular, and sense of belonging in the last place he expected to find it.",
          popularity: 137.811,
          poster_path: "/htTS07IvYv3rv57ftzNEprefwSq.jpg",
          release_date: "2021-03-26",
          title: "A Week Away",
          video: false,
          vote_average: 7.1,
          vote_count: 168,
        },
        {
          adult: false,
          backdrop_path: "/997ToEZvF2Obp9zNZbY5ELVnmrW.jpg",
          genre_ids: [10749, 18, 35],
          id: 537915,
          original_language: "en",
          original_title: "After",
          overview:
            "Tessa Young is a dedicated student, dutiful daughter and loyal girlfriend to her high school sweetheart. Entering her first semester of college, Tessa's guarded world opens up when she meets Hardin Scott, a mysterious and brooding rebel who makes her question all she thought she knew about herself -- and what she wants out of life.",
          popularity: 137.009,
          poster_path: "/u3B2YKUjWABcxXZ6Nm9h10hLUbh.jpg",
          release_date: "2019-04-11",
          title: "After",
          video: false,
          vote_average: 7.2,
          vote_count: 6136,
        },
        {
          adult: false,
          backdrop_path: "/gzycjJWGw04DF6C7IYOA1F0cWhc.jpg",
          genre_ids: [18, 10749],
          id: 694256,
          original_language: "it",
          original_title: "Sulla stessa onda",
          overview:
            "A summer fling born under the Sicilian sun quickly develops into a heartbreaking love story that forces a boy and girl to grow up too quickly.",
          popularity: 148.877,
          poster_path: "/j9O2WXJqF45ynkng4SAsZ1h0OCt.jpg",
          release_date: "2021-03-25",
          title: "Caught by a Wave",
          video: false,
          vote_average: 6.9,
          vote_count: 116,
        },
        {
          adult: false,
          backdrop_path: "/hQQTE285UQB1lLY1XiioQ77LYnC.jpg",
          genre_ids: [16, 35, 10749, 18, 14],
          id: 572154,
          original_language: "ja",
          original_title: "青春ブタ野郎はゆめみる少女の夢を見ない",
          overview:
            "In Fujisawa, Sakuta Azusagawa is in his second year of high school. Blissful days with his girlfriend and upperclassman, Mai Sakurajima, are interrupted by the appearance of his first crush, Shoko Makinohara.",
          popularity: 145.243,
          poster_path: "/7Ai8vNEv4zEveh12JViGikoVPVV.jpg",
          release_date: "2019-06-15",
          title: "Rascal Does Not Dream of a Dreaming Girl",
          video: false,
          vote_average: 8.4,
          vote_count: 253,
        },
        {
          adult: false,
          backdrop_path: "/88J6waYVTta8Qz3iX3qUeWNA5d5.jpg",
          genre_ids: [18, 10749],
          id: 447362,
          original_language: "en",
          original_title: "Life in a Year",
          overview:
            "A 17 year old finds out that his girlfriend is dying, so he sets out to give her an entire life, in the last year she has left.",
          popularity: 131.344,
          poster_path: "/xNcjlHPRNoqbpaYis0Y3zX4Hq0x.jpg",
          release_date: "2020-11-27",
          title: "Life in a Year",
          video: false,
          vote_average: 8.5,
          vote_count: 535,
        },
        {
          adult: false,
          backdrop_path: null,
          genre_ids: [80, 18, 10749],
          id: 796124,
          original_language: "en",
          original_title: "Ride or Die",
          overview:
            'Ashley, a fierce friend to Mandy, takes the phrase "hurt my friend and I\'ll kill you" to the extreme. As the bodies stack up, her mistakes haunt her as Mandy tries to dig up old wounds.',
          popularity: 122.442,
          poster_path: "/77S8LQNkB0se2nk15X1d22QV1d1.jpg",
          release_date: "2021-02-09",
          title: "Ride or Die",
          video: false,
          vote_average: 0,
          vote_count: 0,
        },
        {
          adult: false,
          backdrop_path: "/9wav4lUFPyLEzkOoJiJBSjI8fMm.jpg",
          genre_ids: [16, 10749, 14, 18],
          id: 568160,
          original_language: "ja",
          original_title: "天気の子",
          overview:
            "The summer of his high school freshman year, Hodaka runs away from his remote island home to Tokyo, and quickly finds himself pushed to his financial and personal limits. The weather is unusually gloomy and rainy every day, as if taking its cue from his life. After many days of solitude, he finally finds work as a freelance writer for a mysterious occult magazine. Then, one day, Hodaka meets Hina on a busy street corner. This bright and strong-willed girl possesses a strange and wonderful ability: the power to stop the rain and clear the sky.",
          popularity: 124.445,
          poster_path: "/qgrk7r1fV4IjuoeiGS5HOhXNdLJ.jpg",
          release_date: "2019-06-19",
          title: "Weathering with You",
          video: false,
          vote_average: 8.2,
          vote_count: 984,
        },
        {
          adult: false,
          backdrop_path: "/y7b78soqvJq4aQ8G0Zt72inSQoE.jpg",
          genre_ids: [35, 10749],
          id: 778730,
          original_language: "es",
          original_title: "Loco por ella",
          overview:
            "After a magical night together, Adri voluntarily turns himself into the psychiatric institution where Carla lives.",
          popularity: 103.022,
          poster_path: "/hPBJckYsL1UOsz44InZ2wYJyJTy.jpg",
          release_date: "2021-02-26",
          title: "Crazy About Her",
          video: false,
          vote_average: 7.3,
          vote_count: 267,
        },
        {
          adult: false,
          backdrop_path: "/yBxq43FaskaXDGKWNJQmM75WoGS.jpg",
          genre_ids: [12, 18, 10749],
          id: 514921,
          original_language: "en",
          original_title: "The Aeronauts",
          overview:
            "In 1862, daredevil balloon pilot Amelia Wren teams up with pioneering meteorologist James Glaisher  to advance human knowledge of the weather and fly higher than anyone in history. While breaking records and advancing scientific discovery, their voyage to the very edge of existence helps the unlikely pair find their place in the world they have left far below them. But they face physical and emotional challenges in the thin air, as the ascent becomes a fight for survival.",
          popularity: 90.939,
          poster_path: "/kZHnblqmTBUBgzYBIxWIz9txsEi.jpg",
          release_date: "2019-11-04",
          title: "The Aeronauts",
          video: false,
          vote_average: 6.8,
          vote_count: 723,
        },
        {
          adult: false,
          backdrop_path: "/nN4Gs3vZAOJ1D6FRtrwbU9VGYwU.jpg",
          genre_ids: [16, 10749, 10751],
          id: 486589,
          original_language: "en",
          original_title: "Red Shoes And The Seven Dwarfs",
          overview:
            "Princes who have been turned into Dwarfs seek the red shoes of a lady in order to break the spell, although it will not be easy.",
          popularity: 112.526,
          poster_path: "/MBiKqTsouYqAACLYNDadsjhhC0.jpg",
          release_date: "2019-07-25",
          title: "Red Shoes And The Seven Dwarfs",
          video: false,
          vote_average: 7.6,
          vote_count: 654,
        },
        {
          adult: false,
          backdrop_path: "/hrMbAi9fPTmc6EtpyyAgDKznptu.jpg",
          genre_ids: [10749, 18],
          id: 398818,
          original_language: "en",
          original_title: "Call Me by Your Name",
          overview:
            "In 1980s Italy, a relationship begins between seventeen-year-old teenage Elio and the older adult man hired as his father's research assistant.",
          popularity: 97.469,
          poster_path: "/tcNniniS4rfqrLH0oORikJfnIwY.jpg",
          release_date: "2017-09-01",
          title: "Call Me by Your Name",
          video: false,
          vote_average: 8.3,
          vote_count: 9009,
        },
      ],
      total_pages: 500,
      total_results: 10000,
    },
    status: 200,
    statusText: "",
    headers: {
      "cache-control": "public, max-age=600",
      "content-type": "application/json;charset=utf-8",
    },
    config: {
      url:
        "/discover/movie?api_key=998fbc8cc4dcef8db8fe2fd268686191&with_genres=10749",
      method: "get",
      headers: { Accept: "application/json, text/plain, */*" },
      baseURL: "https://api.themoviedb.org/3",
      transformRequest: [null],
      transformResponse: [null],
      timeout: 0,
      xsrfCookieName: "XSRF-TOKEN",
      xsrfHeaderName: "X-XSRF-TOKEN",
      maxContentLength: -1,
      maxBodyLength: -1,
    },
    request: {},
  },
};
